import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/providers/QueryProvider";
import { AuthProvider } from "@/providers/AuthProvider";
import LayoutBar from "@/components/LayoutBar/LayoutBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {/* Кастомный провайдер без него не сделать запросы TQ */}
        <QueryProvider>
          <AuthProvider>
            {children}
            <LayoutBar />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
