import re

from sqlalchemy import RowMapping, text
from sqlalchemy.orm import Session

WORK_TYPE_SELECT_SQL = """
    SELECT id, name, code, category, default_priority,
           travel_minutes, work_minutes, documents_minutes, norm_minutes
    FROM work_types
"""
# norm_minutes is generated by PostgreSQL and is never written directly.
UPDATABLE_COLUMNS = (
    "name",
    "code",
    "category",
    "default_priority",
    "travel_minutes",
    "work_minutes",
    "documents_minutes",
)


def list_work_types(session: Session) -> list[RowMapping]:
    return list(session.execute(text(WORK_TYPE_SELECT_SQL + " ORDER BY id ASC")).mappings().all())


def find_work_type(session: Session, work_type_id: int) -> RowMapping | None:
    return (
        session.execute(
            text(WORK_TYPE_SELECT_SQL + " WHERE id = :work_type_id"),
            {"work_type_id": work_type_id},
        )
        .mappings()
        .one_or_none()
    )


def lock_work_type(session: Session, work_type_id: int) -> RowMapping | None:
    return (
        session.execute(
            text(WORK_TYPE_SELECT_SQL + " WHERE id = :work_type_id FOR UPDATE"),
            {"work_type_id": work_type_id},
        )
        .mappings()
        .one_or_none()
    )


def find_id_by_name(session: Session, name: str) -> int | None:
    # Matches the case-insensitive unique index uq_work_types_name.
    return session.execute(
        text("SELECT id FROM work_types WHERE lower(name) = lower(:name)"), {"name": name}
    ).scalar_one_or_none()


def find_id_by_code(session: Session, code: str) -> int | None:
    return session.execute(
        text("SELECT id FROM work_types WHERE lower(code) = lower(:code)"), {"code": code}
    ).scalar_one_or_none()


def add_work_type(session: Session, values: dict[str, object]) -> int:
    values_copy = dict(values)
    if "code" not in values_copy or not values_copy["code"]:
        name_str = str(values_copy.get("name", "work_type"))
        slug = re.sub(r"[^a-zA-Z0-9]+", "_", name_str).strip("_").lower()
        values_copy["code"] = slug or "work_type"
    if "category" not in values_copy or not values_copy["category"]:
        values_copy["category"] = "repair"
    if "default_priority" not in values_copy or values_copy["default_priority"] is None:
        values_copy["default_priority"] = 3

    return session.execute(
        text("""
            INSERT INTO work_types (
                name, code, category, default_priority,
                travel_minutes, work_minutes, documents_minutes
            )
            VALUES (
                :name, :code, :category, :default_priority,
                :travel_minutes, :work_minutes, :documents_minutes
            )
            RETURNING id
        """),
        values_copy,
    ).scalar_one()


def update_work_type(session: Session, work_type_id: int, changes: dict[str, object]) -> None:
    columns = [column for column in UPDATABLE_COLUMNS if column in changes]
    # Only whitelisted column names are joined; every value is a bound parameter.
    assignments = ", ".join(f"{column} = :{column}" for column in columns)
    session.execute(
        text(f"UPDATE work_types SET {assignments} WHERE id = :work_type_id"),
        {**{column: changes[column] for column in columns}, "work_type_id": work_type_id},
    )
