"""Add city districts and require a district for every building using SQL.

Revision ID: 0002
Revises: 0001
"""

from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE districts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            city_id INTEGER NOT NULL,
            name VARCHAR(150) NOT NULL,
            CONSTRAINT pk_districts PRIMARY KEY (id),
            CONSTRAINT fk_districts_city_id_cities
                FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE RESTRICT,
            CONSTRAINT ck_districts_name_not_blank CHECK (name = btrim(name) AND name <> ''),
            CONSTRAINT uq_districts_id_city UNIQUE (id, city_id)
        )
    """)
    op.execute("CREATE UNIQUE INDEX uq_districts_city_name ON districts (city_id, lower(name))")
    op.execute("ALTER TABLE streets ADD CONSTRAINT uq_streets_id_city UNIQUE (id, city_id)")
    # This revision is installed on a fresh database, as agreed with the user.
    # PostgreSQL rejects existing buildings rather than assigning an invented district.
    op.execute("""
        ALTER TABLE buildings
            ADD COLUMN city_id INTEGER NOT NULL,
            ADD COLUMN district_id INTEGER NOT NULL
    """)
    op.execute("""
        ALTER TABLE buildings
            DROP CONSTRAINT fk_buildings_street_id_streets,
            ADD CONSTRAINT fk_buildings_street_city
                FOREIGN KEY (street_id, city_id) REFERENCES streets (id, city_id)
                ON DELETE RESTRICT,
            ADD CONSTRAINT fk_buildings_district_city
                FOREIGN KEY (district_id, city_id) REFERENCES districts (id, city_id)
                ON DELETE RESTRICT
    """)
    op.execute("CREATE INDEX ix_buildings_district_id ON buildings (district_id)")


def downgrade() -> None:
    op.execute("""
        ALTER TABLE buildings
            DROP CONSTRAINT fk_buildings_district_city,
            DROP CONSTRAINT fk_buildings_street_city,
            ADD CONSTRAINT fk_buildings_street_id_streets
                FOREIGN KEY (street_id) REFERENCES streets (id) ON DELETE RESTRICT
    """)
    op.execute("DROP INDEX ix_buildings_district_id")
    op.execute("ALTER TABLE buildings DROP COLUMN district_id, DROP COLUMN city_id")
    op.execute("ALTER TABLE streets DROP CONSTRAINT uq_streets_id_city")
    op.execute("DROP TABLE districts")
