"""Create users, worker profiles, skill catalog, and refresh tokens tables.

Revision ID: 0003
Revises: 0002
"""

from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            name VARCHAR(100) NOT NULL,
            surname VARCHAR(100) NOT NULL,
            lastname VARCHAR(100) NULL,
            username VARCHAR(50) NOT NULL,
            password_hash VARCHAR(255) NOT NULL,
            role VARCHAR(20) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_users PRIMARY KEY (id),
            CONSTRAINT ck_users_name_not_blank CHECK (name = btrim(name) AND name <> ''),
            CONSTRAINT ck_users_surname_not_blank CHECK (
                surname = btrim(surname) AND surname <> ''
            ),
            CONSTRAINT ck_users_lastname_not_blank_if_present CHECK (
                lastname IS NULL OR (lastname = btrim(lastname) AND lastname <> '')
            ),
            CONSTRAINT ck_users_username_not_blank CHECK (
                username = btrim(username) AND username <> ''
            ),
            CONSTRAINT ck_users_password_hash_not_blank CHECK (
                password_hash = btrim(password_hash) AND password_hash <> ''
            ),
            CONSTRAINT ck_users_role_valid CHECK (role IN ('observer', 'worker'))
        )
    """)
    op.execute("CREATE UNIQUE INDEX uq_users_username ON users (lower(username))")

    op.execute("""
        CREATE TABLE workers (
            user_id INTEGER NOT NULL,
            workshift_start TIME NOT NULL,
            workshift_end TIME NOT NULL,
            CONSTRAINT pk_workers PRIMARY KEY (user_id),
            CONSTRAINT fk_workers_user_id_users
                FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
            CONSTRAINT ck_workers_workshift_duration_not_zero CHECK (
                workshift_start <> workshift_end
            )
        )
    """)

    op.execute("""
        CREATE TABLE worker_skills (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            skill VARCHAR(100) NOT NULL,
            CONSTRAINT pk_worker_skills PRIMARY KEY (id),
            CONSTRAINT uq_worker_skills_skill UNIQUE (skill),
            CONSTRAINT ck_worker_skills_skill_not_blank CHECK (
                skill = btrim(skill) AND skill <> ''
            )
        )
    """)

    op.execute("""
        CREATE TABLE worker_skill_assignments (
            worker_id INTEGER NOT NULL,
            skill_id INTEGER NOT NULL,
            CONSTRAINT pk_worker_skill_assignments PRIMARY KEY (worker_id, skill_id),
            CONSTRAINT fk_worker_skill_assignments_worker
                FOREIGN KEY (worker_id) REFERENCES workers (user_id) ON DELETE CASCADE,
            CONSTRAINT fk_worker_skill_assignments_skill
                FOREIGN KEY (skill_id) REFERENCES worker_skills (id) ON DELETE RESTRICT
        )
    """)
    op.execute(
        "CREATE INDEX ix_worker_skill_assignments_skill_id ON worker_skill_assignments (skill_id)"
    )

    op.execute("""
        CREATE TABLE refresh_tokens (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            user_id INTEGER NOT NULL,
            token_hash VARCHAR(255) NOT NULL,
            expires_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            revoked_at TIMESTAMPTZ NULL,
            CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
            CONSTRAINT fk_refresh_tokens_user_id_users
                FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
        )
    """)
    op.execute("CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id)")
    op.execute("CREATE UNIQUE INDEX uq_refresh_tokens_token_hash ON refresh_tokens (token_hash)")


def downgrade() -> None:
    op.execute("DROP TABLE refresh_tokens")
    op.execute("DROP TABLE worker_skill_assignments")
    op.execute("DROP TABLE worker_skills")
    op.execute("DROP TABLE workers")
    op.execute("DROP TABLE users")
