"""Add ticket assignments, comments, push subscriptions, and notification outbox.

Revision ID: 0004
Revises: 0003
"""

from alembic import op

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE ticket_assignments (
            ticket_id INTEGER NOT NULL,
            worker_id INTEGER NOT NULL,
            assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_ticket_assignments PRIMARY KEY (ticket_id, worker_id),
            CONSTRAINT fk_ticket_assignments_ticket_id_tickets
                FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE CASCADE,
            CONSTRAINT fk_ticket_assignments_worker_id_workers
                FOREIGN KEY (worker_id) REFERENCES workers (user_id) ON DELETE CASCADE
        )
    """)
    op.execute("CREATE INDEX ix_ticket_assignments_worker_id ON ticket_assignments (worker_id)")

    op.execute("""
        CREATE TABLE ticket_comments (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            ticket_id INTEGER NOT NULL,
            author_id INTEGER NOT NULL,
            text TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_ticket_comments PRIMARY KEY (id),
            CONSTRAINT fk_ticket_comments_ticket_id_tickets
                FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE CASCADE,
            CONSTRAINT fk_ticket_comments_author_id_users
                FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
            CONSTRAINT ck_ticket_comments_text_not_blank
                CHECK (text = btrim(text) AND text <> ''),
            CONSTRAINT ck_ticket_comments_text_length CHECK (char_length(text) <= 4000)
        )
    """)
    op.execute("CREATE INDEX ix_ticket_comments_ticket_id ON ticket_comments (ticket_id)")
    op.execute("CREATE INDEX ix_ticket_comments_author_id ON ticket_comments (author_id)")

    op.execute("""
        CREATE TABLE push_subscriptions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            user_id INTEGER NOT NULL,
            token TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_push_subscriptions PRIMARY KEY (id),
            CONSTRAINT fk_push_subscriptions_user_id_users
                FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
            CONSTRAINT uq_push_subscriptions_token UNIQUE (token),
            CONSTRAINT ck_push_subscriptions_token_not_blank
                CHECK (token = btrim(token) AND token <> ''),
            CONSTRAINT ck_push_subscriptions_token_length CHECK (char_length(token) <= 4096)
        )
    """)
    op.execute("CREATE INDEX ix_push_subscriptions_user_id ON push_subscriptions (user_id)")

    op.execute("""
        CREATE TABLE notification_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            recipient_id INTEGER NOT NULL,
            ticket_id INTEGER NOT NULL,
            kind VARCHAR(40) NOT NULL,
            data JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            websocket_delivered_at TIMESTAMPTZ NULL,
            push_delivered_at TIMESTAMPTZ NULL,
            attempt_count INTEGER NOT NULL DEFAULT 0,
            next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            last_error TEXT NULL,
            CONSTRAINT pk_notification_events PRIMARY KEY (id),
            CONSTRAINT fk_notification_events_recipient_id_users
                FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE,
            CONSTRAINT fk_notification_events_ticket_id_tickets
                FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE CASCADE,
            CONSTRAINT ck_notification_events_kind_valid
                CHECK (kind IN ('ticket_assigned', 'ticket_status_changed')),
            CONSTRAINT ck_notification_events_attempt_count_nonnegative
                CHECK (attempt_count >= 0)
        )
    """)
    op.execute(
        "CREATE INDEX ix_notification_events_recipient_id ON notification_events (recipient_id)"
    )
    op.execute("CREATE INDEX ix_notification_events_ticket_id ON notification_events (ticket_id)")
    op.execute("""
        CREATE INDEX ix_notification_events_pending_push
        ON notification_events (push_delivered_at, next_attempt_at, id)
    """)


def downgrade() -> None:
    op.execute("DROP TABLE notification_events")
    op.execute("DROP TABLE push_subscriptions")
    op.execute("DROP TABLE ticket_comments")
    op.execute("DROP TABLE ticket_assignments")
