"""Add brigades and active worker memberships.

Revision ID: 0006
Revises: 0005
"""

from alembic import op

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE users DROP CONSTRAINT ck_users_role_valid")
    op.execute("""
        ALTER TABLE users
        ADD CONSTRAINT ck_users_role_valid
        CHECK (role IN ('observer', 'foreman', 'worker'))
    """)

    op.execute("""
        CREATE TABLE brigades (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            name VARCHAR(100) NOT NULL,
            foreman_id INTEGER NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_brigades PRIMARY KEY (id),
            CONSTRAINT fk_brigades_foreman_id_users
                FOREIGN KEY (foreman_id) REFERENCES users (id) ON DELETE RESTRICT,
            CONSTRAINT ck_brigades_name_not_blank CHECK (name = btrim(name) AND name <> '')
        )
    """)
    op.execute("CREATE UNIQUE INDEX uq_brigades_name ON brigades (lower(name))")
    op.execute("CREATE UNIQUE INDEX uq_brigades_foreman_id ON brigades (foreman_id)")

    op.execute("""
        CREATE TABLE brigade_members (
            brigade_id INTEGER NOT NULL,
            worker_id INTEGER NOT NULL,
            CONSTRAINT pk_brigade_members PRIMARY KEY (brigade_id, worker_id),
            CONSTRAINT fk_brigade_members_brigade_id_brigades
                FOREIGN KEY (brigade_id) REFERENCES brigades (id) ON DELETE CASCADE,
            CONSTRAINT fk_brigade_members_worker_id_workers
                FOREIGN KEY (worker_id) REFERENCES workers (user_id) ON DELETE CASCADE
        )
    """)
    op.execute("CREATE UNIQUE INDEX uq_brigade_members_worker_id ON brigade_members (worker_id)")


def downgrade() -> None:
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM users WHERE role = 'foreman') THEN
                RAISE EXCEPTION
                    'Cannot downgrade brigade migration while foreman users exist';
            END IF;
        END $$;
    """)
    op.execute("DROP TABLE brigade_members")
    op.execute("DROP TABLE brigades")
    op.execute("ALTER TABLE users DROP CONSTRAINT ck_users_role_valid")
    op.execute("""
        ALTER TABLE users
        ADD CONSTRAINT ck_users_role_valid
        CHECK (role IN ('observer', 'worker'))
    """)
