"""Add service_area_id to Office

Revision ID: b4b4a9a49709
Revises: 0025
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b4b4a9a49709'
down_revision: str | None = '0025'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offices', sa.Column('service_area_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_offices_service_area_id'), 'offices', ['service_area_id'])
    op.create_foreign_key(
        op.f('fk_offices_service_area_id_service_areas'),
        'offices',
        'service_areas',
        ['service_area_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_offices_service_area_id_service_areas'), 'offices', type_='foreignkey'
    )
    op.drop_constraint(op.f('uq_offices_service_area_id'), 'offices', type_='unique')
    op.drop_column('offices', 'service_area_id')
    # ### end Alembic commands ###
